Title: JavaScript TDD
Standards:
  - Title: JavaScript TDD
    UID: 784ff209-114b-48b5-bf63-f937ed88ea1d
    Description: Getting started with TDD in JavaScript.
    SuccessCriteria:
      - Explain why TDD adherents write tests
      - Describe the three stages of the TDD process
      - Identify pure and impure functions
    ContentFiles:
      - Type: Instructor
        UID: 78c10303-76e3-4920-9bf1-006326bc1523
        Path: /units/00-javascript-tdd/00-readme.md
      - Type: Instructor
        UID: 3610142d-7b76-4dc2-8462-70eccb24c8e4
        Path: /units/00-javascript-tdd/lesson-plans/usaa-lesson-plan.md
        DefaultVisibility: hidden
      - Type: Lesson
        UID: f96bf6c9-2a78-4860-8211-1b1b50cd9769
        Path: /units/00-javascript-tdd/01-unit-overview.md
      - Type: Lesson
        UID: 02892209-488b-4f12-841a-2991278c30a6
        Path: /units/00-javascript-tdd/02-vocabulary.md
      - Type: Checkpoint
        UID: 25b0ea4a-1fe9-44a4-b7e3-569d1382eb73
        Path: /checkpoints/javascript-tdd-checkpoint.md
        Autoscore: false
